name: PyPi Publish

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      -
        name: Build package
        run: python -m build
      -
        name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  update-stable-branch:
    needs: [main]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: Checkout stable branch
        uses: actions/checkout@v3
        with:
          ref: stable
          fetch-depth: 0
      -
        name: Update stable branch to release tag & push
        run: |
          git reset --hard ${{ github.event.release.tag_name }}
          git push
